# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r

r:
  - oldrel
  - release
  - devel

warnings_are_errors: false
cache: packages

before_install:
  - set -e
  - mkdir -p ~/Downloads
  - curl -L https://julialang-s3.julialang.org/bin/linux/x64/1.4/julia-1.4.2-linux-x86_64.tar.gz -o "$HOME/Downloads/julia.tar.gz"
  - tar -xvzf "$HOME/Downloads/julia.tar.gz" -C "$HOME/Downloads"
  - cp -r "$(find "$HOME/Downloads" -maxdepth 2 -name "julia*" -type d | head -n 1)" "$HOME/julia"
  - rm -rf ~/Downloads/julia*
  - export PATH="$HOME/julia/bin:$PATH"
  - export R_LD_LIBRARY_PATH="$(R RHOME)/lib:$HOME/julia/lib/julia"
  - echo 'insecure' >> $HOME/.curlrc # 'fix' certificate problems

install:
  - R -e 'install.packages("devtools")'
  - R -e 'devtools::install_deps(dep = TRUE)'
  - R -e 'JuliaCall::julia_setup()'

after_success:
  # - Rscript -e 'covr::codecov()'
  - Rscript -e 'pkgdown::build_site()'

#deploy:
#  provider: pages
#  skip-cleanup: true
#  github-token: $GH_PAT
#  keep-history: true
#  local-dir: docs
#  on:
#    branch: master
