# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - oldrel
  - release
  - devel

warnings_are_errors: true
cache: packages

r_packages:
  - covr
  - devtools
  - pkgdown

before_install:
  - sudo sudo apt install julia

script:
  - Rscript -e 'library(badr); setup()'
  - R CMD build .
  - R CMD check *tar.gz

after_success:
  - Rscript -e 'library(covr); covr::codecov()'
