# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - oldrel
  - release
  - devel

warnings_are_errors: true
cache: packages

r_packages:
  - covr
  - devtools
  - pkgdown

before_install:
  - set -e
  - mkdir -p ~/Downloads
  - curl -L https://julialang-s3.julialang.org/bin/linux/x64/1.4/julia-1.4.2-latest-linux-x86_64.tar.gz -o "$HOME/Downloads/julia.tar.gz"
  - tar xzf "$HOME/Downloads/julia.tar.gz" -C "$HOME/Downloads"
  - cp -r "$(find "$HOME/Downloads" -maxdepth 2 -name "julia*" -type d | head -n 1)" "$HOME/julia"
  - rm -rf ~/Downloads/julia*
  - export PATH="$HOME/julia/bin:$PATH"
  - export R_LD_LIBRARY_PATH="$(R RHOME)/lib:$HOME/julia/lib/julia"

script:
  - set -e
  - R CMD build .
  - R CMD INSTALL *.tar.gz
  - Rscript -e 'badr::setup_julia_package()'
  - R CMD check --as-cran *.tar.gz

after_success:
  - Rscript -e 'library(covr); covr::codecov()'
  - Rscript -e 'pkgdown::build_site()'

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_PAT
  keep-history: true
  local-dir: docs
  on:
    branch: master
